add vesting contract example (time lock)
aiken-lang/site pull request #8
Opened 2023-01-04 16:08 UTC by matiwinnetou

2023-01-04 17:35 UTC, KtorZ requested changes
Haven't reviewed the Aiken script yet, will do tomorrow.

2023-01-04 17:35 UTC, KtorZ commented on src/pages/getting-started/vesting.mdx
> +</Callout>
Same here, let's remove.

2023-01-04 17:35 UTC, KtorZ commented on src/pages/getting-started/vesting.mdx
> +  const Datum = Data.Object({
Indentation is off on that one.

2023-01-05 08:28 UTC, matiwinnetou commented on src/pages/getting-started/vesting.mdx
> +# Setting up wallets and getting funds
I simply changed and added explanation to the existing section:
"Vesting Contract (time lock)!"

2023-01-05 08:37 UTC, matiwinnetou commented on src/pages/getting-started/vesting.mdx
> +```
You mean to split this into multiple files or isolate tests only into another file?

2023-01-05 09:37 UTC, KtorZ commented on src/pages/getting-started/vesting.mdx
> +```
I mean, in the documentation; show it as multiple logical chunks; rather than one big piece. I can do some edits directly if you don't mind.

2023-01-05 12:18 UTC, matiwinnetou commented on src/pages/getting-started/vesting.mdx
> +```
Please do edits directly, I don't mint at all.

2023-01-06 06:10 UTC, KtorZ commented
Did some edits, and added some useful functions (`and` and `or`) to the `stdlib` though they unveiled a new issue with the compiler captured as _acceptance test 38_. So, will wait until this test is fixed before moving on with the PR. 

Thanks for the contribution @matiwinnetou 🙏

2023-01-09 17:26 UTC, merged