update hello world tutorial
aiken-lang/site pull request #97
Opened 2024-11-16 05:32 UTC by jinglescode

@KtorZ, I made a few changes here:
- update hello world tutorial to use `MeshTxBuilder` instead of `Transaction` for future proofing
- after Chang, reference script fee calculation requires fetcher
- use TypeScript instead
- added a link to the code example so anyone and test
- remove tangocrypto, its not live anymore

2024-11-16 15:18 UTC, KtorZ requested changes
Thanks for this @jinglescode, it was on my TODO list lately. It looks good, except for the `bf.key` file. Please do not encourage people to write their private API keys on the filesystem, especially in a git working tree :') ... 

So I reverted those changed back to using an ENV var; which likely messes up a bit with the code highlight indices. Haven't re-checked those.

2024-11-16 15:18 UTC, KtorZ commented on src/pages/example--hello-world/end-to-end/mesh.mdx
> +);
```suggestion
const blockchainProvider = new BlockfrostProvider(process.env.BLOCKFROST_PROJECT_ID);
```

Let's keep the ENV var here, thanks 🙏

2024-11-16 15:18 UTC, KtorZ commented on src/pages/example--hello-world/end-to-end/mesh.mdx
> +preview...
```suggestion
export BLOCKFROST_PROJECT_ID=preview...
```

2024-11-16 15:18 UTC, KtorZ commented on src/pages/example--hello-world/end-to-end/mesh.mdx
> +Note that the highlighted line above looks Blockfrost project ID, so we create a file named `bf.key` and add your Blockfrost project ID to it.
```suggestion
<Callout type="warning">
Note that the highlighted line above looks for an environment variable named `BLOCKFROST_PROJECT_ID` which its value must be set to your Blockfrost project id.
You can define a new environment variable in your terminal by running (in the same session you're also executing the script!):
```

2024-11-16 15:18 UTC, KtorZ commented on src/pages/example--hello-world/end-to-end/mesh.mdx
```suggestion
</Callout>

```

2024-11-16 15:18 UTC, KtorZ commented on src/pages/example--hello-world/end-to-end/mesh.mdx
> +);
```suggestion
const blockchainProvider = new BlockfrostProvider(process.env.BLOCKFROST_PROJECT_ID);
```

2024-11-16 15:18 UTC, KtorZ commented on src/pages/example--hello-world/end-to-end/mesh.mdx
> +);
```suggestion
const blockchainProvider = new BlockfrostProvider(process.env.BLOCKFROST_PROJECT_ID);
```

2024-11-16 15:18 UTC, KtorZ commented on src/pages/example--hello-world/end-to-end/mesh.mdx
> +You can find the [full source code](https://github.com/MeshJS/examples/tree/main/aiken-hello-world) for this tutorial on GitHub.
```suggestion
You can find the [full source code](https://github.com/MeshJS/examples/tree/main/aiken-hello-world) for this tutorial on MeshJS's GitHub.
```

2024-11-17 09:17 UTC, jinglescode commented
looking good. thanks for reviewing.

2024-11-17 10:46 UTC, KtorZ approved these changes

2024-11-17 10:46 UTC, merged

2024-11-19 06:22 UTC, jinglescode commented
@KtorZ the live site is not updated.